# 阵列建立的途径

## 零与壹的世界

In [1]:
# 导入numpy数学库
import numpy as np

 1. [ ] 建立一个新的 2x2 整数阵列，2x2 是阵列的形状，不需要初始化阵列里的内容。

In [2]:
np.empty((2, 2))

array([[1.49166815e-154, 4.33627255e-311],
       [3.50977942e+064, 2.78134232e-309]])

 2. [ ] 要想获得一个 `array([1,2,3], [4,5,6], dtype=int32)` 结果，建立一个新的阵列，与`X`有同样的形状与类型。

In [3]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
np.empty_like(X)

array([[          0,   536870912,  2092767113],
       [-2147481605,  2092761090, -1073739781]], dtype=int32)

 3. [ ] 建立一个 3D 阵列，其中对角线上都是 1，其它位置上数据都是 0 。

In [4]:
# d = np.zeros((3, 3), dtype=np.float)
# np.fill_diagonal(d, 1)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 4. [ ] 建立一个新的阵列，形状是 2x3 采用浮点数类型，值都是 1 。

In [6]:
np.ones(shape=(3,2), dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

 5. [ ] 设 `x = np.arange(4, dtype=np.int64)`，建立一个形状相同、类型相同的阵列，阵列的值都是`1`，该阵列存储在`X`变量中。

In [7]:
x = np.arange(4, dtype=np.int64)
X = np.ones_like(x)
X, X.dtype

(array([1, 1, 1, 1]), dtype('int64'))

 6. [ ] 建立一个新的`3x2`浮点数阵列，阵列的值都是`0`。

In [8]:
np.zeros((3,2), dtype=np.float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

 7. [ ] 设 `x = np.arange(4, dtype=np.int64)`，建立一个值都是`0`的形状相同、类型相同的阵列，并存储到`X`变量中。

In [9]:
x = np.arange(4, dtype=np.int64)
X = np.zeros_like(x)
X, X.dtype

(array([0, 0, 0, 0]), dtype('int64'))

 8. [ ] 建立一个新的`2x5`阵列，阵列的的单位是`uint32`，值都是`6`。

In [10]:
np.full((2,5), 6, dtype=np.uint32)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [11]:
np.zeros((2,5), dtype=np.uint32) + 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

 9. [ ] 设`x = np.arange(4, dtype=np.int64)`，建立一个相同形状相同类型的阵列，其中阵列的值都是`6`，并存储在变量`X`里。

In [12]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6])

In [13]:
x = np.arange(4, dtype=np.int64)
X = np.ones_like(x) + 5
X, X.dtype

(array([6, 6, 6, 6]), dtype('int64'))

## 现有的数据

 1. [ ] 建立一个`[1, 2, 3]`的阵列。

In [14]:
np.array([1,2,3])

array([1, 2, 3])

 2. [ ] 设`x = [1, 2]`，把`x`变成一个阵列。

In [15]:
x = [1,2]
np.asarray(x)

array([1, 2])

 3. [ ] 设`X = np.array([[1, 2], [3, 4]])`，把X变成一个矩阵。

In [16]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

 4. [ ] 设`x = [1, 2]`，把`x`变成一个浮点阵列。

In [17]:
x = [1, 2]
np.asfarray(x)

array([1., 2.])

In [18]:
x = [1, 2]
np.asarray(x, dtype=np.float)

array([1., 2.])

 5. [ ] 设`x = np.array([30])`，把`x`变成自身单个元素的标量值，例如，`30`。

In [19]:
x = np.array([30])
np.asscalar(x)

30

In [20]:
x = np.array([30])
x[0]

30

 6. [ ] 设`x = np.array([1, 2, 3])`，建立一个`x`阵列的副本，显示出不同的阵列id以示不同。

In [21]:
x = np.array([1, 2, 3])
print(id(x), x)
X = x.copy()
print(id(X), X)

4459033184 [1 2 3]
4459032864 [1 2 3]


## 数字范围

 1. [ ] 建立一个`2, 4, 6, 8, ..., 100`的阵列。

In [22]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

 2. [ ] 建立一个1D的50个均分阵列，范围是从`3.`到`10.`且包含`10.`。

In [23]:
np.linspace(3., 10., 50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

 3. [ ] 建立一个1D的50个均分阵列，经过log标量化后，范围在`3.`到`10.`之间，不包含`10.`。

In [24]:
np.logspace(3., 10., 50, endpoint=False)

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

## 绑定矩阵

 1. [ ] 设`X = np.array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11]])`，得`X`的对角线值，也就是`[0, 5, 10]`。

In [25]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diagonal(X)

array([ 0,  5, 10])

In [26]:
np.diag(X)

array([ 0,  5, 10])

 2. [ ] 建立一个2D阵列，其中对角线值等于`[1, 2, 3, 4]`，其它位置上的值都是`0`。

In [27]:
x = np.zeros((4, 4))
np.fill_diagonal(x, [1,2,3,4])
x

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [28]:
np.diagflat([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

 3. 建立一个像下面一样的阵列。
`array([[ 0.,  0.,  0.,  0.,  0.], [ 1.,  0.,  0.,  0.,  0.], [ 1.,  1.,  0.,  0.,  0.]])`

In [29]:
np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

 4. [ ] 建立一个像下面一样的阵列。`array([[ 0,  0,  0], [ 4,  0,  0], [ 7,  8,  0], [10, 11, 12]])`

In [30]:
x = np.arange(1, 13)
y = np.array_split(x, 4)
np.tril(np.array(y), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [31]:
np.tril(np.arange(1, 13).reshape(4, 3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

 5. [ ] 建立一个像下面一样的阵列。`array([[ 1,  2,  3], [ 4,  5,  6], [ 0,  8,  9], [ 0,  0, 12]])`

In [32]:
x = np.arange(1, 13)
y = np.array_split(x, 4)
np.triu(np.array(y), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [33]:
np.triu(np.arange(1, 13).reshape(4, 3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])